# Generated by Django 5.1.6 on 2025-02-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(default='Unknown', max_length=100)),
                ('createdAt', models.DateField()),
                ('image', models.ImageField(upload_to='blog')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='place_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('timetotravel', models.CharField(default='2 days')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.category')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('tour_overview', models.TextField()),
                ('tour_highlights', models.JSONField()),
                ('whats_included', models.JSONField(null=True)),
                ('itinerary', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('must_try_food', models.JSONField()),
                ('recommended_guides', models.JSONField(null=True)),
                ('faqs', models.JSONField(null=True)),
                ('image1', models.ImageField(upload_to='details_images/')),
                ('image2', models.ImageField(upload_to='details_images/')),
                ('image3', models.ImageField(upload_to='details_images/')),
                ('image4', models.ImageField(upload_to='details_images/')),
                ('image5', models.ImageField(upload_to='details_images/')),
                ('map_image', models.ImageField(null=True, upload_to='maps/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.place')),
            ],
        ),
    ]
